# Generated by Django 5.0.4 on 2024-04-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок заказа', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Описание заказа', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания заказа', verbose_name='Создан')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Цена заказа', max_digits=10, verbose_name='Цена')),
                ('customer', models.ForeignKey(help_text='Заказчик', on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile', verbose_name='Заказчик')),
                ('freelancer', models.ForeignKey(blank=True, help_text='Фрилансер', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.freelancerprofile', verbose_name='Фрилансер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
